### ISSUE TITLE
Wrong Person Detected 

### ISSUE THREAD

**Issue by raja259** [estebanuri/face_recognition#12]
Hi
I have implemented your code in my application  very successfully and I really appreciate you for the effort you have put in providing this code.

Now my problem is if a person is in database then it recognize him or her properly but if he is a new face which is not in the database still it recognizes as some one else.

I have tried with a database of 350 users and every unknown entry it recognize as some or other name from the database. 

Please help and tell me what mistake I have been doing .

Thanks 
Raja

**Comment by raja259** [comment]
I think it is related to the confidence level what will be the best confidence level one should check  for best results

**Comment by estebanuri** [comment]
Hi raja259

How did you generate the dataset? 
The images that are indexed must have the same characteristics as those used in runtime.

To have better accuracy, I recommend you try the following strategies:

- align the faces (ie, rotate them so that the eyes always appear in the same position)

- reduce the threshold (depends on the application, if it is preferable to avoid false positives at all costs, it is advisable to have a lower threshold)

- allow only faces with a certain size (if they are far away, ask them to get closer)

- index multiple faces of the same person (~ 10 faces looking up / down, and in combined directions)

**Comment by raja259** [comment]
Thanks problem solved as per your suggestion

**Comment by mbpatel6245** [comment]
@raja259 which changes have you made to improve the result can you please help me on that?

**Comment by h3clikejava** [comment]
The recognition rate is very low

**Comment by Gatisha05** [comment]
Hello @raja259 
I need your help with this project regarding how you improved the results as well as how you store your dataset. Can we connect in telegram or mail please.

Thanks
Gatisha
Mail Id :- gatishaa2@gmail.com
telegram :- https://t.me/Gatisha_Agrawal
